# 语言设置: zh, en
language: zh

# 全局设置
settings:
  # 两次按键触发的最小间隔（秒）
  # 设置为 0 则关闭冷却
  cooldown: 1.5

key-binds:
  open_menu:
    trigger: SWAP_HAND
    require-shift: false
    command: "cd"
    permission: "soda.keybind.use"
  
  spawn_teleport:
    trigger: SWAP_HAND
    require-shift: true
    command: "spawn"
    permission: "soda.keybind.use"
